name: Build pdf

on:
  pull_request:

permissions:
  contents: read

jobs:
  build_pdf:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Compile Typst
        uses: lvignoli/typst-action@main
        with:
          source_file: |
            main.typ
